/**
 * Would You Rather Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OptionEnum from './OptionEnum';

/**
 * The CreateUserSchema model module.
 * @module model/CreateUserSchema
 * @version 0.1.0
 */
class CreateUserSchema {
    /**
     * Constructs a new <code>CreateUserSchema</code>.
     * @alias module:model/CreateUserSchema
     * @param name {String} 
     */
    constructor(name) { 
        
        CreateUserSchema.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>CreateUserSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserSchema} obj Optional instance to populate.
     * @return {module:model/CreateUserSchema} The populated <code>CreateUserSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserSchema();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('avatarURL')) {
                obj['avatarURL'] = ApiClient.convertToType(data['avatarURL'], 'String');
            }
            if (data.hasOwnProperty('questions')) {
                obj['questions'] = ApiClient.convertToType(data['questions'], ['String']);
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], {'String': OptionEnum});
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CreateUserSchema.prototype['id'] = undefined;

/**
 * @member {String} name
 */
CreateUserSchema.prototype['name'] = undefined;

/**
 * @member {String} avatarURL
 */
CreateUserSchema.prototype['avatarURL'] = undefined;

/**
 * @member {Array.<String>} questions
 */
CreateUserSchema.prototype['questions'] = undefined;

/**
 * @member {Object.<String, module:model/OptionEnum>} answers
 */
CreateUserSchema.prototype['answers'] = undefined;






export default CreateUserSchema;

