/**
 * Would You Rather Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WouldYouRatherBackend);
  }
}(this, function(expect, WouldYouRatherBackend) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WouldYouRatherBackend.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('createUserUsersCreatePost', function() {
      it('should call createUserUsersCreatePost successfully', function(done) {
        //uncomment below and update the code to test createUserUsersCreatePost
        //instance.createUserUsersCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserUsersDeleteUserIdDelete', function() {
      it('should call deleteUserUsersDeleteUserIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteUserUsersDeleteUserIdDelete
        //instance.deleteUserUsersDeleteUserIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsersAllGet', function() {
      it('should call getAllUsersAllGet successfully', function(done) {
        //uncomment below and update the code to test getAllUsersAllGet
        //instance.getAllUsersAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserUsersGetUserIdGet', function() {
      it('should call getUserUsersGetUserIdGet successfully', function(done) {
        //uncomment below and update the code to test getUserUsersGetUserIdGet
        //instance.getUserUsersGetUserIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('indexRouteUsersGet', function() {
      it('should call indexRouteUsersGet successfully', function(done) {
        //uncomment below and update the code to test indexRouteUsersGet
        //instance.indexRouteUsersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserUsersUpdatePut', function() {
      it('should call updateUserUsersUpdatePut successfully', function(done) {
        //uncomment below and update the code to test updateUserUsersUpdatePut
        //instance.updateUserUsersUpdatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
